AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-covid

  Sample SAM Template for sam-covid

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Covid19ServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: covid_server/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Covid19Server:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /model
            Method: post
      Layers:
          - arn:aws:lambda:us-east-2:259788987135:layer:AWSLambda-Python37-SciPy1x:10

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Covid19ServerApi:
    Description: "API Gateway endpoint URL for Prod stage for Covid19 Server function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  Covid19ServerFunction:
    Description: "Covid19 Server Lambda Function ARN"
    Value: !GetAtt Covid19ServerFunction.Arn
  Covid19ServerFunctionIamRole:
    Description: "Implicit IAM Role created for Covid19 Server function"
    Value: !GetAtt Covid19ServerFunctionRole.Arn
